### ISSUE TITLE
Errors occurred after run 'hexo s'

### ISSUE THREAD

**Issue by lonelee-kirsi** [sabrinaluo/hexo-theme-replica#10]
## The Errors

```bash
Unhandled rejection TypeError: D:\works\blog\github_pages\themes\replica\layout\index.ejs:1
 >> 1| <%
    2| var posts = page.posts.data;
    3| var oldestPostDate = posts.length ? posts[posts.length - 1].date : {date: moment()};
    4| var startFrom = oldestPostDate.format('MMM D, YYYY');

Cannot read property 'github' of undefined
    at eval (eval at compile (D:\works\blog\github_pages\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:14:27)
    at returnedFn (D:\works\blog\github_pages\node_modules\ejs\lib\ejs.js:580:17)
    at _compiled (D:\works\blog\github_pages\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (D:\works\blog\github_pages\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\works\blog\github_pages\node_modules\hexo\lib\hexo\index.js:390:25
    at tryCatcher (D:\works\blog\github_pages\node_modules\bluebird\js\release\util.js:16:23)
    at D:\works\blog\github_pages\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\works\blog\github_pages\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

## Questions
- Why ?
- How to fix it ?

**Comment by sabrinaluo** [comment]
Which version of `Hexo` did you use?
Do you have the required `social` section in your `_config.yml`? If you don't have any link, you will still need to put below code snippet in your `_config.yml`
```
social:
  github: 
  weibo: 
  linkedin:
```

**Comment by lonelee-kirsi** [comment]
- I‘m using `Hexo 3.3.8`.

-  I have configured it like this:

   ```yaml
    social:
      github: https://github.com/lonelee-kirsi
      weibo: https://github.com/lonelee-kirsi
      linkedin: https://github.com/lonelee-kirsi
   ```
   But it’s still the same errors.
